---

- name: disable selinux
  selinux:
    state: disabled
  
  notify:
     - reboot system
- name: stop firwall and disable
  service:
    name: firewalld
    state: stopped
    enabled: false
- name: disable vm swappiness
  sysctl:
    name: vm.swappiness
    value: '1'
    state: present
- name: disable kernel transparent_hugepage
  command: "{{ item }}"
  with_items:
    - 'echo never > /sys/kernel/mm/transparent_hugepage/defrag'
    - 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'

