---
- name: download the tar file of  mysql_jdbc driver
  unarchive:
    src: https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.46.tar.gz
    dest: /home/admin
    remote_src: true

- name: create a directory  name java
  file:
    dest: /usr/share/java
    state: directory
- name: copy the bin.jar file to /usr/share/java
  command: cp /home/admin/mysql-connector-java-5.1.46/mysql-connector-java-5.1.46-bin.jar /usr/share/java/mysql-connector-java.jar


- name: update package
  yum:
    name: '*'
    state: latest


