---
- name: Install ntp
  yum:
    name: ntp
    state: present

- name: Set timezone to Asia/kolkata
  timezone:
    name: Asia/Kolkata

- name: Configure ntp file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf

  notify:
    - restart ntp

- name: Start the ntp service
  service:
    name: ntpd
    state: started
    enabled: true

